name: MaestroCI Build Bot
language: generic
sudo: required
services:
  - docker
before_install:
  - docker pull baalajimaestro/android_build:latest
  - docker run -d -p 127.0.0.1:80:4567 baalajimaestro/android_build:latest /bin/sh -c "cd /root/android_build;"
script:
- bash ./build.sh -i rr -U https://github.com/ResurrectionRemix/platform_manifest.git -B pie -b xiaomi -d whyred -r
steps:
- name: test
  image: baalajimaestro/android_build:latest
env:
  global:
    TELEGRAM_TOKEN:
      secret: TELEGRAM_TOKEN
    TELEGRAM_CHAT:
      secret: TELEGRAM_CHAT
    GH_REPO_NAME:
      secret: GH_REPO_NAME
    GH_PERSONAL_TOKEN:
      secret: GH_PERSONAL_TOKEN
  commands:
  - bash ./build.sh -i rr -U https://github.com/ResurrectionRemix/platform_manifest.git -B pie -b xiaomi -d whyred -r
