language: generic
dist: trusty
services:
  - docker
before_install:
  - docker pull baalajimaestro/android_build:latest
  - docker run -d baalajimaestro/android_build
jobs:
  include:
    - stage: test
      script:
        - docker exec bash ./build.sh -i rr -U https://github.com/ResurrectionRemix/platform_manifest.git -B pie -b xiaomi -d whyred -r
