language: generic
dist: trusty
services:
  - docker
before_install:
  - docker pull baalajimaestro/android_build:latest
  - docker run baalajimaestro/android_build /bin/sh  -c "./build.sh -i rr -U https://github.com/ResurrectionRemix/platform_manifest.git -B pie -b xiaomi -d whyred -r
"
jobs:
  include:
    - stage: test
      script:

