version: 2.1
jobs:
  build:
    docker:
      - image: baalajimaestro/android_build:latest
    steps:
      - run:
          name: Build
          command: source ./build.sh -i rr -U https://github.com/ResurrectionRemix/platform_manifest.git -B pie -b xiaomi -d whyred -r
