kind: pipeline
name: MaestroCI Build Bot
node:
  instance: android-buildbot
jobs:
  build:
    docker:
      - image: baalajimaestro/android_build:latest
steps:
- name: test
  image: baalajimaestro/android_build:latest
  environment:
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    TELEGRAM_CHAT:
      from_secret: TELEGRAM_CHAT
    GH_REPO_NAME:
      from_secret: GH_REPO_NAME
    GH_PERSONAL_TOKEN:
      from_secret: GH_PERSONAL_TOKEN
  commands:
  - bash ./build.sh -i rr -U https://github.com/ResurrectionRemix/platform_manifest.git -B pie -b xiaomi -d whyred -r